Relax octokit version dependency
prontolabs/pronto pull request #433
Opened 2022-09-15 14:48 UTC by andriusm

Previous constrain was limiting where Danger 9.x cannot be used together with Pronto in a project because of different octokit dependency version requirements. There was also an issue registered suggesting this - https://github.com/prontolabs/pronto/issues/430

2022-09-15 14:51 UTC, avelicka approved these changes

2022-09-15 14:51 UTC, avelicka approved these changes

2022-09-16 03:48 UTC, ashkulz requested changes

2022-09-16 03:48 UTC, ashkulz commented on lib/pronto/version.rb
> -    STRING = '0.11.0'.freeze
Please don't change this.

2022-09-16 03:48 UTC, ashkulz commented on pronto.gemspec
> +  s.add_runtime_dependency('octokit', '~> 5.0')
```suggestion
  s.add_runtime_dependency('octokit', '>= 4.7.0')
```
Maybe just remove the `~> 4.7` part?

2022-09-16 06:18 UTC, andriusm commented
Changed octokit dependency to be `>= 4.7.0` and removed several versions of Ruby from the build matrix which were failing. Octokit version 5.0 dropped support for Ruby versions 2.0, 2.1, 2.2, 2.3, 2.4, 2.5 and 2.6, which have all reached end-of-life.

2022-11-08 15:37 UTC, tomasv approved these changes

2022-11-09 04:46 UTC, ashkulz requested changes
I wouldn't like to drop support for Ruby 2.6 although it's EOL, because that's the currently supported JRuby version.

Dropping support for old Ruby versions will also be problematic, as that'll require a major version bump. Is there a way to fix the CI without doing all this?

2022-11-23 06:44 UTC, ashkulz commented
Any update, @andriusm?

2022-12-31 06:42 UTC, closed without merging